name: CI-Arduino-Esp8266
on: [workflow_dispatch, push]


jobs:
  Arduino-ESP8266:
    runs-on: ubuntu-latest
    env:
      TARGET: nodemcuv2
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install dependencies
      run: |
        arduino-cli core update-index
        curl https://arduino.esp8266.com/stable/package_esp8266com_index.json --output /home/runner/.arduino15/package_esp8266com_index.json
        arduino-cli core install -v esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli lib install -v ArduinoJson
        arduino-cli lib install -v --git-url https://github.com/CHOUAiB/Esp-GitHub-OTA.git

    - name: Compile Sketch
      run: arduino-cli compile -b esp8266:esp8266:${{ env.TARGET }}
      working-directory: examples/esp8266
