name: CI-PlatformIO-Esp32
on: [workflow_dispatch, push]


jobs:
  PlatformIO-ESP32:
    runs-on: ubuntu-latest
    env:
      TARGET: nodemcu-32s # Must match the value after colon in platformio.ini (line 4: [env:nodemcu-32s])
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e ${{ env.TARGET }}
      working-directory: .
