name: Auto-Create-PIO-ESP32

#on: [workflow_dispatch, push]
on: [workflow_dispatch]

jobs:
  PlatformIO-ESP32:
    runs-on: ubuntu-latest
    env:
      TARGET: esp32 # Must match the value after colon in platformio.ini (line 4: [env:nodemcu-32s])
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e ${{ env.TARGET }}
      working-directory: .
      
    - name: Store Artifacts
      uses: actions/upload-artifact@v3
      with:
          name: firmware
          path: .pio/build/*/firmware.bin
          retention-days: 1
          
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%h %d %Y - %H:%M:%S')"
      
  release:
    name: Release
    # if: startsWith(github.event.ref, 'refs/tags/v')
    needs: PlatformIO-ESP32
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for CHANGELOG
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: firmware
      # - name: Display structure of downloaded files
      #   run: ls -R
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "firmware/*/firmware*.bin"
          bodyFile: "CHANGELOG.md"
